version: '3'

services:
  node-app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    networks:
      - node-app
  nginx:
    image: nginx:latest
    volumes:

volumes:
  mongo-data:
    name: ${VOLUME_ID}

networks:
  node-app:
    driver: bridge
