const API_URL_DEV = process.env.REACT_APP_API_URL_DEV;
const API_URL_PROD = process.env.REACT_APP_API_URL_PROD;
const CLIENT_DOMAIN_DEV = process.env.REACT_APP_CLIENT_DOMAIN_DEV;
const CLIENT_DOMAIN_PROD = process.env.REACT_APP_CLIENT_DOMAIN_PROD;

export { API_URL_DEV, API_URL_PROD, CLIENT_DOMAIN_DEV, CLIENT_DOMAIN_PROD };
